
import React from "react";
import Button from "../components/Button";
import Image from "next/image";
import Thumb from "./../../public/pngtree-blue-cram-school-border-summer-training-course-image_789185.jpg";

export const metadata = {
    title: "Create Next About",
    description: "Generated by create next app",
  };

const About = () => {
  //   throw new Error("There was an huge error.");

  return (
    <>
      <h1 className="text-red-500">
        Hi! This is <b className="text-green-500 underline">About</b> page
      </h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris quis ex
        iaculis, ornare libero sit amet, convallis urna. Vivamus nisl odio,
        venenatis ut vehicula at, convallis quis justo. Fusce sodales libero vel
        scelerisque faucibus. Proin accumsan elit nibh, sed sollicitudin ante
        congue in. Phasellus blandit ex sit amet purus dignissim, in accumsan
        metus aliquam. Curabitur ac nisl vitae augue sodales interdum.
      </p>
      <div className="w-[400px]">
        <Image src={Thumb} alt="Course_image" placeholder="blur" />
      </div>

      <Button />
    </>
  );
};

export default About;
